---
title: "Data Literacy: two day workshop"
format: gfm
---

<!-- Do not modify the README.md file directly. -->

<!-- Instead edit the README.qmd file -->

## tl;dr

Looking for teaching materials?
[Here](session-materials/resources-rendered/)

## Repo folder structure

-   `session-materials`
    -   Contains the notes and resources for the workshop.
    -   There are three folder names resources-\*\*\*.
        -   `resources-teaching/` contains the raw `.qmd` documents for teaching crib sheets.
        -   `resources-student/` contains the raw `.qmd` documents for student facing materials / handouts.
        -   `resources-rendered/` contains all resources rendered in `.html` format.
    -   Notes are named with a prefix such as *d1-s1* which indicate the notes for day 1 session 1.
    -   All files named `crib-sheet` contain various questions and prompts for instructor use.
    -   `instructor_resources.html` contains links to all materials required by instructors to run the workshop.
    -   `all-da-plotz.html` is a cheatsheet of plots than can be used at various points to illustrate issues if questions arise.
    -   `glossary.html` contains a glossary of statistical terms for participants' use.
    -   `pdf` file contain *d2-s2* case studies and are optional formats for distributing to participants.
-   `app`
    -   Contains the app that accompanies the *d2-s1* notes.
    -   The app can be found at [cc-stats.shinyapps.io/uncertainty](https://cc-stats.shinyapps.io/uncertainty)

## Workshop Curriculum

-   See [codeclan.github.io/data_literacy](https://www.https://codeclan.github.io/data_literacy) for student landing page
-   Day 1 Session 1:
    -   **Partly lecture-based facilitated discussion**
    -   Friendly intro session
    -   Interpreting visual data.
    -   Misleading with data.
    -   Correlation vs causation.
    -   Numerical reasoning - absolutes, percentages and relative values.
-   Day 1 Session 2:
    -   **Guided discussion based on simple scenarios**
    -   Defining uncertainty.
    -   Where uncertainty occurs in practice.
    -   Engaging with uncertainty.
    -   Case study
-   Day 2 Session 1
    -   **Hands-on workshop**
    -   Exploring data scenarios likely to occur in the real world.
    -   Students work in groups to explore visual data.
    -   Apply knowledge developed in sessions 1 and 2 to answer questions posed in the workshop.
-   Day 2 Session 2:
    -   **Guided discussion based on case studies**
    -   Introduction to modelling and different types of models.
    -   Explore how models are simplifications.
    -   Importance of updating models.
    -   Students will follow scenarios to identify and create different types of example models.
