---
title: 'Data Visualization<span style="color: #e6c372;">_</span>'
format: 
  html:
    toc: true
    mainfont: Gilroy
    fontsize: 1.4rem
    canononical: true
css: style.css
---

::: {.callout-important icon="false" collapse="true"}
## Notes to instructor

These notes are not intended to prescribe how a session should progress.
How things go will depend on participant knowledge, willingness to share and engagement.
To get the most from the participants it might be necessary to give them lots of space to open up.

The notes are structured with headers that can be used to guide discussion.
Under each header there is a short sentence start to kick the brain into motion.
They sections are presented in a logical order, but do not have to be followed in that order if the discussion takes things differently.
Be familiar with the ToC for quick navigation if necessary.

The answers obtained from one section can / should be referred back to in later sections.
This means there are often no "satisfying" conclusions at the end of one section.
It is important, therefore to record contributions on the board to refer back to often.

### Callouts

Red callouts are for instructor guidance.

Blue callouts contain discussion prompts, questions, and things that you might want to steer the participants towards if they go to far off-piste.
:::

## Learning outcomes

-   Understand how to choose the most appropriate plots
-   Understand best practice regarding audience interpretation
-   Improve understanding of misleading effects / tricks
-   Learn alternatives to misleading choices

## Intro

The types of things we shall cover:

-   What types of plot have you used?
-   Are there other types may not have used but have come across?
-   What you like / dislike to see in a visualization?
    -   (e.g. colour palettes / visual effects)
-   Are the
-   What have you seen other people do?

## Types of plot

Let's start by generating just a list of plot types - I'll start you off with **scatter plot**.

::: {.callout-important icon="false" collapse="true"}
## Collection of example plot images

-   If using physical which board can tile these images on the screen.\
-   If using e.g. excalidraw, can copy-paste these images straight in.\
-   Which ever method, you should be able to align images with participant's notes.

**Image Links**

-   [Scatter](images/scatter.png){.external target="_blank"}
-   [Bar](images/funnel-vs-bar2--bar.png){.external target="_blank"}
-   [Funnel](images/funnel-vs-bar1--funnel.png){.external target="_blank"}
-   [Pie](images/pie_three_cats.png){.external target="_blank"}
-   [Line](images/interest-rates-c.png){.external target="_blank"}
-   [Combination](images/d2-s2--growth-plot.png){.external target="_blank"}

(could maybe also add traffic lights / bullets / dumbbells / dot-plots / lollipops / histograms / boxplots / etc...)
:::

::: {.callout-note icon="false"}
## Put them up somewhere visible

-   write answers on board / whiteboard app
-   if using a physical board
    -   consider writing on post-its, to allow easy re-positioning
    -   taking a photo of the board before cleaning might be a good idea
:::

## How do you decide what type of plot to use?

How you choose to present your data can have a huge impact on how much your audience engages with your message.

::: {.callout-note icon="false"}
## Plot choices

-   Depends on type of data
    -   Why?
    -   What types of data might you have to deal with?
-   depends on who will be consuming the visualization
    -   Why?
    -   **Devil's advocate question:** Shouldn't we try to make all plots as simple to understand as possible? If so, isn't the easiest plot to understand for all audiences? - Thoughts: Maybe, but a more knowledgeable / experienced audience can usually process more complex graphics faster.
-   depends on what message you want to highlight
    -   The same data can be represented in different ways to highlight different aspects.
    -   There are certain conventions that we are used to seeing.\
:::

## How do different plots convey information differently?

There are certain conventions we are used to seeing on plots.
For example, it is usual to put time on the x axis - putting time the y axis would be a real obstacle to interpreting a chart quickly.

::: {.callout-note icon="false"}
## Conventions / expectations

Can you think of other conventions / expectations the audience might bring with them?

-   Use of colour?
-   Ordering bars according to value (ascending / descending)
-   Horizontal vs vertical charts
-   Legends / keys
-   Annotations - e.g. adding values directly onto bars / pie segments
-   etc
:::

::: {.callout-important icon="false" collapse="true"}
## Style thoughts

Participants should be able to come up with some / all of the below, and maybe some others.
Any not mentioned by them do not have to be raised here by the instructor - let the thoughts percolate.
We will cover all these things in the next part of the session

-   Colours
    -   Red = bad; green = good?
    -   Red = Loss; green = profit?
    -   Red = Labour; Blue = Conservative
    -   Red = hot; Blue = cold
    -   Does colour add anything to a plot?
    -   Colour intensity: more intense = higher or lower?
-   RAG status - if people are used to looking at a RAG status, they might bring expectations with them about what those colours mean.
-   Your audience expects you to make it easy for them to understand your message.
    -   this is why some of the most common pitfalls can lead to hugely misleading graphics
    -   and why some bad actors do this on purpose
-   Lines generally mean points are related (e.g. points connected over time)
:::

## Stylistic choices

We have already discussed some of the choices you might face when designing an appropriate visualization.
Beyond just selecting the best type of chart, we also have the ability to make stylistic / aesthetic choices for our visualizations.

::: {.callout-important icon="false" collapse="true"}
## Bring up 3D / info graphics

Hopefully people will start talking about info-graphics, 3D effects and general presentation.
These are things we will give specific guidance on later, so might be good to ensure they are surfaced here.

The main point here, I think, should be to bring out as many of these choices as possible, rather than focusing on whether they are good or bad ideas.
That will come later, and is why writing on the whiteboard board / post-its should be an ongoing thing.

This might also be a good point to get some ratings on how much people like the ideas mentioned - e.g. find out if everyone loves 3D bar charts with bars on two separate axes!
:::

::: {.callout-note icon="false"}
## Stylistic choices

-   What sort of stylistic choices or effect do you like to apply to your plots.
-   How does your audience affect your aesthetics decisions
:::

## Wrap it up

::: {.callout-important icon="false"}
## Summary

No notes here because it will really depend on what ideas were surfaced during the session

Our aim should be to collate and summarize the, hopefully multitudinous, post-it notes.

Recap the progression through the discussion, calling stronger attention to the concepts that will be covered after a break.
:::
