---
title: "Marketing Analytics: case study"
subtitle: 'Allrecipies'
format: 
  html: default
  pdf: default
---

## Allrecipes

As the world's biggest digital food brand, Allrecipes has 18 websites and more than 85 million users.
But the brand also has plenty of competition from other food-focused apps and websites.

To stay ahead of other recipe sites and ensure that it continues to provide all the solutions that users want, Allrecipes relies on marketing analytics.

With marketing analytics, the digital brand can better understand the customer journey and analyze trends as they emerge.
As this Allrecipes case study explains, the brand can expand its audience and attract even more lucrative demographics using these insights.

### Goal

To continue to gain ground as the world's top digital food brand, Allrecipes established several wide-ranging goals.

Some of the brand's primary objectives included the following.

#### Improve user experience

With more than a billion and a half visitors across the brand's sites every year, Allrecipes generates a ton of traffic.
But the company needed a way to understand how visitors were using the site, so it could improve the user experience and gauge the health of the sites.

#### Increase video engagement

To take advantage of a demand for video content, Allrecipes had decided to invest heavily in video.
However, the video production team needed strategic guidance.
The brand needed to know what types of content would drive the most engagement.

#### Drive mobile engagement

To continue to meet the needs of its user base, Allrecipes had to look beyond its websites.
As more and more people began using mobile devices to access the brand's content, Allrecipes realized that the company needed to optimize its mobile app.

#### Inform product strategy

To promote new features and integrations or pursue partner programs, Allrecipes needed to know what its community wanted.
Had they adopted the new integrations yet?
Did they need new features to use the site or app more effectively?

#### Expand user base

Cooking and dining trends come and go, and Allrecipes needed a simple yet effective way to identify these developments.

By responding quickly to trends, the brand would be able to capture a larger user base, including elusive millennials.

#### Grow advertising revenue

Like many digital brands, Allrecipes has a native advertising program that allows the company to monetize its website.
The company aimed to increase its advertising revenue, yet the organization didn't want to compromise the user experience.
To find the right partners to grow this program, Allrecipes needed deeper insights into its audience.

### Process

Although the brand's goals were varied, the approach was relatively straightforward.
To process marketing analytics from a wide range of channels, the brand opted to use Tableau, a business intelligence platform.

With Tableau, Allrecipes could establish a single platform for visualizing data from Adobe Marketing Cloud, Hitwise, and comScore.
By linking Adobe Marketing Cloud to Tableau, the brand could pull in all of its website and marketing analytics.
By linking Hitwise and comScore, the brand could source demographic data.

Using Tableau allowed Allrecipes to build custom dashboards and develop tailored reports to answer all of the brand's questions.
This tool also allowed the brand to pursue collaboration options across the organization.

In fact, departments ranging from marketing and design to product and finance contributed to the tool.
Teams used Tableau Server to publish dashboards, creating a single space where stakeholders could visualize or analyze data.

### Outcome

With Tableau, Allrecipes was able to visualize the brand's data successfully, enabling smarter decisions and making progress toward key goals.
Here's what the brand accomplished using marketing analytics: Improve user experience

Using insights from Tableau, Allrecipes was able to see how visitors typically used the site---including how they submit recipes, share content, and post links on social media channels.
The organization then used this data to devise a plan for improving the site.

Knowing how visitors were already engaging with the site allowed the brand to make data-driven, goal-focused decisions.

#### Increase video engagement

With Tableau's marketing analytics, Allrecipes found that out of all types of recipes, dessert typically generated more views and attracted more comments and photos.
As a result, the brand opted to focus on this highly engaging niche, creating a separate video hub for dessert recipes.
Drive mobile engagement

To increase engagement on mobile devices, Allrecipes devised an A/B test that displayed the brand's mobile site on all devices.
Then the organization used the analytics to identify what drove interactions on mobile.
The brand then used insights to improve the mobile site, including optimizing content and encouraging photo uploads.

#### Inform product strategy

Tableau's data visualizations helped Allrecipes understand trends in its user community and respond to preferences more efficiently.
Using these insights, the brand was able to promote integrations and features while gathering data for future product enhancements.

#### Expand user base

By using Tableau's insights to process trends, Allrecipes was able to segment audiences for various recipe types, ultimately identifying millennial users' interests and preferences.
The brand was then able to create more content geared toward this growing user base---likely responding much more quickly than competitors could.

#### Grow advertising revenue

By tapping into real-time marketing analytics, Allrecipes was able to share popular recipe searches and trending content with its advertising partners during a recent holiday season.
Advertisers could then create ads tailored to these interests, generating a better ROI and creating a more appealing experience for users.
