---
title: "Marketing Analytics: case study"
subtitle: 'Progressive Insurance'
format: 
  pdf: default
  html: default
---

In the early 2000s, Progressive's website was routinely considered one of the best in the insurance industry.
When the insurance provider's customers began switching to mobile devices a decade later, the organization aimed to develop a mobile app as effective as its desktop site.

But what did that mean exactly?
And what was the insurance provider's mobile app missing?

To determine what would make the mobile app more successful, Progressive pursued an in-depth analysis of the organization's marketing data.

### Goal

As Progressive Data & Analytics Business Leader Pawan Divakarla explains, the insurance provider's analytics team has always sought insight into how customers are using the company's tools.

In his words, "At Progressive, we sell insurance. But if you think about it, our product is actually data."

After launching the mobile app, Progressive began looking for ways to optimize the user experience.
As this Progressive case study explains, the organization aimed to streamline the login process and improve user satisfaction to meet its ultimate goals of increasing customer loyalty and new customer acquisition.

### Process

Because Progressive's mobile app generated so much information, the organization needed data visualization tools for collection and processing.
To analyse customers' experiences and actions, the company opted to use a combination of Google Analytics 360 and Google Tag Manager 360.

This choice was a relatively simple one for Progressive because the company already used these tools to run A/B tests and optimize its website.

Using Google's analytical tools to review the company's mobile app would allow Progressive to understand what features to test and how to optimize the user experience across countless mobile devices and operating systems.

Progressive used the two Google tools for separate yet complementary functions:

-   With Google Analytics 360, Progressive could track user sessions and demographics. The company integrated BigQuery for more insight into user behaviours.
-   With Google Tag Manager 360, Progressive could easily implement tracking tags to measure various actions, conversions, and navigation patterns.

To get the insights the company needed to improve its mobile app, Progressive took a three-pronged approach:

#### User device data

First, Progressive aimed to identify which devices and operating systems were most common among the app's user base.
With this information, the company would be able to develop more effective tests for its mobile app.

#### App crash data

Next, Progressive wanted to analyse app crash data.
The company planned to use Google Analytics 360 and BigQuery data to understand the cause for the crash and how users reacted when the app stopped working abruptly.

#### Login and security data

Finally, Progressive aimed to learn how users responded when failed login attempts locked them out of the app.
The company planned to use Google Analytics 360 and BigQuery to see what actions users took.
It planned to then test new prompts that would guide users more effectively.

### Outcome of this marketing analytics case study

Using marketing analytics tools, Progressive was able to process customer behaviour, identify appropriate tests, and implement successful solutions.

Here's how each of the three approaches generated useful results that helped Progressive reach its ultimate acquisition and loyalty goals.

#### User device data

First, Progressive developed session-based reports that reflected the most common mobile devices and operating systems for the app's user base.
With those insights, the company identified which device and operating system combinations to prioritize for its mobile app tests.

As a result, the company reduced testing time by 20% for its mobile app---allowing the organization to find solutions much more quickly than its typical timeline would have allowed.

#### App crash data

Next, Progressive reviewed the actions customers took right before the app crashed.
The company pinpointed a server issue as the cause of a major crash that disrupted countless mobile app sessions.

Using this data, Progressive could address the server issue and prevent it from happening again.

#### Login and security data

Finally, Progressive created a custom funnel in Google Analytics 360 to evaluate users' typical login path.
After learning that many users who became locked out of their accounts never attempted to log in again, the company developed a workflow that provided better guidance.

The new workflow sends users to a Forgot Password page, which has increased logins by 30%.
