---
title: 'Glossary'
subtitle: 'of statistical terms'
---

A very brief description of the statistical terms encountered during this workshop.
The terms are listed in, roughly, the order in which we encounter them, rather than alphabetically.
To find a particular term quickly, press <kbd>Ctrl</kbd> + <kbd>F</kbd> and start typing the term your are looking for.

## Statistical terms {#stats-terms}

Population

:   Every possible individual element that we might be interested interested in measuring.

Sample

:   A subset of the population.
    We usually cannot measure the entire population, so we take a sample and assume it is a close-enough approximation of the population.

Sample size

:   The number of observation taken form the population.
    Larger is always better.

Spread

:   A description of the variability of the data.
    Other related terms include; **variance** and **standard deviation**.

Parameter

:   A number that describes some characteristic of a population.

Statistic

:   A number that describes some characteristic of a sample.
    Statistics are used because we usually don't know the true underlying value of a population.

Descriptive statistic

:   A value that summarizes the data down to a single number.
    The value is a standalone representation of the data, from which no underlying processes are supposed.

Confidence interval

:   A range of plausible values centred around a statistic of interest.
    For example, consider a margin of error around an estimate.

Frequency

:   A count: the number of times a given outcome occurs.

Accuracy

:   How close a value is to its true value.
    For example how close an estimate is to a population parameter.

Precision

:   How repeatable a measurement is.
    For example how varied are repeated measurements.

Probability

:   The chance that a particular outcome occurs.
    Probabilities range from 0 - 1, and are analogous to percentages.

Distribution

:   A distribution is a list of all of the possible outcomes of a random variable along with either their corresponding frequency or probability values.

Frequency distribution

:   Can sometimes be visualized as a bar chart of the number of times a given outcome can happen.

Probability distribution

:   Similar to a frequency distribution but shows the probability of a particular outcome of occurring.

Cumulative distribution function (CDF)

:   The cumulative sum of the probabilities of all possible values.

Probability density function (PDF)

:   A function that estimates the probability that a variable is close to a value of interest.

## Modelling terms

System / process

:   The thing we are interested in learning about.

Model

:   A simplified representation of a system or process, constructed with the aim of generating some insight about the system.
    Models can be diagrammatic, mathematical, or statistical, and can be used for a variety of different purposes.

Conceptual model

:   Often represented in diagram format, such as a flowchart.
    May be referred to as frameworks.

Descriptive model

:   A model that describes a how a system works, perhaps by highlighting a relationship, without requiring any underlying theory to justify it.
    (See also **descriptive statistic**.)

Explanatory model

:   A model that attempts to quantify some aspect of a system, and show how different components are related, in an attempt to explain something of how the system works.

Predictive model

:   A model that, based on data available now, attempts to reveal what will happen at a later time.
